config/routes.rb
Rails.application.routes.draw do
  
  # Devise
  # ------
  devise_for :users
  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  #   put 'users' => 'devise/registrations#update', :as => 'user_registration'
  # end
  
  # welcomes controller
  # -------------------
  get 'welcomes/index'

  # contents controller
  # -------------------
  get 'contents/committee'
  get 'contents/event'
  get 'contents/promote'
  # get 'contents/gallery'

  # contacts controller
  # -------------------
  match 'contents/contact', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]

  # photos controller
  # -----------------
  resources :photos, only: [:create, :destroy]
  match 'contents/gallery', to: 'photos#new_multiple', via: 'get'

  root to: 'welcomes#index'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Notunpalli Query",
      :to => "surabhee.saha@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  dragonfly_accessor :image
 
  validates :image, presence: true
  validates_size_of :image, maximum: 500.kilobytes,
                    message: "should be no more than 500 KB", if: :image_changed?
 
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable#, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      # flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
      redirect_to root_url, notice: 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # respond_to :html, :js
  def new
    @photos = Photo.order('created_at DESC')
    @photo = Photo.new
  end
 
  def create
    respond_to do |format|
      @photo = Photo.new(photo_params)
      @photo.save
      format.html {redirect_to contents_gallery_path}
      format.js
    end
  end

  def new_multiple
    @photos = Photo.order('created_at DESC')
    @photo = Photo.new
  end

  def year_2014
    new_multiple
  end

  def year_2013
    new_multiple
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    else
      flash[:error] = "Selected photo could not be deleted."
    end
  end
 
  private
 
  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # def javascript(*files)
  #   content_for(:head) { javascript_include_tag(*files) }
  # end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/contacts/new.html.erb
<div class='contents'>
  <h1>CONTACT</h1>
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
  <div class='row'>
    <div class='col-sm-4'>
      <div class='column col-sm-12'>
        <div class="form-group">
          <%= f.text_field :name, :required => true, autofocus: true, class: 'form-control', placeholder: 'Name' %>
        </div>
      </div>

      <div class='column col-sm-12'>
        <div class="form-group">
          <%= f.email_field :email, :required => true, class: 'form-control', placeholder: 'Email' %>
        </div>
      </div>

      <div class='column col-sm-12'>
        <div class="form-group">
          <%= f.text_area :message, :required => true, class: 'col-xs-12', rows: '5', class: 'form-control', placeholder: 'Message' %>
        </div>
      </div>

      <div class='column col-sm-12'>
        <div class="form-group">
          <%= f.button :submit, 'SEND', :class=> "btn btn-primary", id: 'send-msg-btn' %>
        </div>
      </div>
    </div>
    <div class='col-sm-8'>
      <div class='map-container'>
        <div id="gmap_canvas"></div>
      </div>
      <script type="text/javascript"> function init_map(){var myOptions = {zoom:18,center:new google.maps.LatLng(19.064558353232318,72.83355876715086),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(19.064558353232318, 72.83355876715086)});infowindow = new google.maps.InfoWindow({content:"<b>Notunpalli Durgotsab</b><br/>Municipal Garden<br/>400050 Bandra West" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);
      </script>
    </div>
  </div>
  <% end %>
</div>

app/views/contents/committee.html.erb
<div class='committee-page'>
  <h1>MANAGING COMMITTEE</h1>
  <div class='row'>
    <div class='col-lg-12' id='managing-committee-members-wrapper'>
      <div class='col-md-4'>
        <%= image_tag("shakti.jpg", class: 'img-thumbnail', height: '150') %>
        <p>Shakti Samanta</p>
      </div>
      <div class='col-md-4'>
        <%= image_tag("burman.jpg", class: 'img-thumbnail', height: '150') %>
        <p>R D Burman</p>
      </div>
      <div class='col-md-4'>
        <%= image_tag("pramod.png", class: 'img-thumbnail', height: '150') %>
        <p>Pramod Chakravarty</p>
      </div>
    </div>
    <div class='col-md-7' id='committee-align'>
      <h4>MANAGING COMMITTEE</h4>
      <p>(Registered Under Public Trust Act)</p>
      <p>(Regd. No. 4655 of 1977)(New P.T.R. No. A3172) PAN AAATN 5241L</p>
      <p>Regd. U/S 80G of IT Act. 1961 No. DIT(E)/MC/80G/1005/2011-12</p>
      <p>dt. 29.09.2011 Valid w.e.f. 17.01.2011</p>
      
      <div class='col-sm-6'>
        <h5>President</h5>
        <p>Shri Basu Chatterjee</p>
      </div>
      <div class='col-sm-6'>
        <h5>Patron in Chief</h5>
        <p>Dr. J.N. Banerjee</p>
      </div>

      <div class='col-sm-12'>
        <h5>Vice Presidents</h5>
        <div class='col-sm-4'>
          <p>Shri M.K. Modak</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri J. Acharya</p>
        </div>
        <div class='col-sm-4'>
          <p>Capt. R.K. Basu</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Deepak Mitra</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Surjit Roy</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Bilin Sen</p>
        </div>
      </div>

      <div class='col-sm-12'>
        <h5>General Secretary</h5>
        <p>Shri M.C. Banerjee</p>
      </div>

      <div class='col-sm-6'>
        <h5>Joint Secretaries</h5>
        <div class='col-sm-6'>
          <p>Shri P.K. Goon</p>
        </div>
        <div class='col-sm-6' id='height-adj'>
          <p>Shri Sankar Maitra</p>
        </div>
      </div>
      <div class='col-sm-6'>
        <h5>Treasurer</h5>
        <p>Shri A.K. Banerjee</p>
      </div>
      <div class='col-sm-12'>
        <h5>Members Managing Committee</h5>
        <div class='col-sm-4'>
          <p>Shri Kaushik Modak</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Kaushik Saha</p>
        </div>
        <div class='col-sm-4' class='height-adj'>
          <p>Shri Romi Bidichandani</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Supratik Roy</p>
        </div>
        <div class='col-sm-4'>
          <p>Smt. Mahua Indolkar</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Barun Sarkar</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Samudra Sen</p>
        </div>
        <div class='col-sm-4'>
          <p>Smt. Sanchali Sarkar</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Manilal Bhutta</p>
        </div>
        <div class='col-sm-4'>
          <p>Capt. Swapan Paul</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Nabakumar Daas</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Amit Dutta</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri A.K. Ganguly</p>
        </div>
        <div class='col-sm-4'>
          <p>Shri Subhojit Dasgupta</p>
        </div>
        <div class='col-sm-4' id='height-adj'>
          <p>Shri Subroto Chakroborty</p>
        </div>
      </div>
      <div class='col-sm-12'>
        <p class='table-foot' id='margin-realign'>Auditor - M/s. A.H. Desai, Chartered Accountant</p>
        <p class='table-foot'>(Audited accounts upto the year 31-03-2012 are available in the committee's office for inspection by members)</p>
      </div>

    </div>
    <div class='col-md-5'>
      <div class='col-md-12'>
        <%= image_tag("man-comm.jpg", class: 'img-thumbnail', width: '350') %>
      </div>
      <div class='col-md-12'>
        <%= image_tag("ladies-wing.jpg", class: 'img-thumbnail', width: '350') %>
      </div>
      <div class='col-md-12'>
        <%= image_tag("senior-ladies.jpg", class: 'img-thumbnail', width: '350') %>
      </div>
    </div>
  </div>
</div>

app/views/contents/donate.html.erb
<div class='container'>
  <div class='contents'>
    <h1>DONATION</h1>
  </div>
</div>

app/views/contents/event.html.erb
<div class='event-page'>
  
  <h1>EVENTS</h1>
  
  <div class="row">
    <div class="col-md-5" class='event-align'>
      <h3>Puja (2014)</h3>
      <%= render 'partials/event_agenda' %>
      <p class='table-footer'>
        Timing subject to change as per the priest's advice.
      </p>
      <p class='table-footer'>
        Bhog: October 1, 2014 - October 3, 2014 | 1:30 pm
      </p>
    </div>
    
    <div class="col-md-7" class='event-align'>
      <h3>Cultural Programme</h3>
      <p class='table-footer'>
        September 29, 2014 - October 3, 2014 | 8:00pm <em>onwards</em>
      </p>
      <%= render 'partials/event_cultural' %>
    </div>
  </div>
</div>

app/views/contents/promote.html.erb
<div class='container'>
  <div class='contents'>
    <h1>Advertisements and Promotions page</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Notunpalli" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Notunpalli" %>">
  <title>Notunpalli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Arimo|Josefin+Slab:400,600,700|Raleway|Inconsolata', :media => "all" %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyA-jjtAeX1jtRQ8i5rSSP71N2x_kBl8yC4" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'photos' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <script>
      $(document).ready(function(){
        $('.carousel').carousel();
      });
    </script>
    <div class="pull-right user-info">
     <% if current_user %>
       Hi <%= current_user.first_name.capitalize %>! <%#= link_to edit_user_registration_path, class: 'btn btn-mini' do %>
              <!-- <i class="glyphicon glyphicon-edit"></i> -->
            <%# end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
              <i class="glyphicon glyphicon-log-out"></i>
            <% end %>
     <%# else %>
       <%#= link_to "Sign In", new_user_session_path %> <!-- or 
       <%#= link_to "Sign Up", new_user_registration_path %> -->
     <% end %>
    </div>

    <%= render 'partials/flash_messages' %>
    
    <div class='page-header'>
      <div id='logo'>
        <%= link_to root_path do %>
          <%= image_tag "logo.png", class: 'resize' %>
        <% end %>
      </div>
      <div id="page-title">
        <p>NOTUNPALLI DURGOTSAB</p>
      </div>
    </div>

    <%= render "partials/navbar" %>

<%= yield %>
  </div>
  <footer id="footer">
    Copyright <%= Time.now.year %> @ Notunpalli Sarbojonin Durgotsab Committee. All Rights Reserved.
  </footer>

</body>
</html>

app/views/partials/_event_agenda.html.erb
<div class="row">
  <div class="col-sm-6">
    <p id='event'>Maha Panchami</p>
  </div>
  <div class="col-sm-6">
    <p id='italic'>September 29, 2014</p>
  </div>
</div>
<div class='table-responsive'>
  <table class='table table-hover'>
    <tr>
      <td>Bodhan</td>
      <td class='dtime'>6:00 pm</td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class="row">
  <div class="col-sm-6">
    <p id='event'>Maha Sashthi</p>
  </div>
  <div class="col-sm-6">
    <p id='italic'>September 30, 2014</p>
  </div>
</div>
<div class='table-responsive'>
  <table class='table table-hover'>
    <tr>
      <td>Kalparambha</td>
      <td class='dtime'>7:00 am</td> 
    </tr>
    <tr>
      <td>Amantran & Adhibas</td>
      <td class='dtime'>6:00 pm</td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class="row">
  <div class="col-sm-6">
    <p id='event'>Maha Saptami</p>
  </div>
  <div class="col-sm-6">
    <p id='italic'>October 1, 2014</p>
  </div>
</div>
<div class='table-responsive'>
  <table class='table table-hover'>
    <tr>
      <td>Naba Patrika & Puja</td>
      <td class='dtime'>7:00 am</td> 
    </tr>
    <tr>
      <td>Pushpanjali</td>
      <td class='dtime'>9:00 am</td> 
    </tr>
    <tr>
      <td>Prasad</td>
      <td class='dtime'>9:30 am</td> 
    </tr>
    <tr>
      <td>Aarti</td>
      <td class='dtime'>7:00 pm</td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class="row">
  <div class="col-sm-6">
    <p id='event'>Maha Astami</p>
  </div>
  <div class="col-sm-6">
    <p id='italic'>October 2, 2014</p>
  </div>
</div>
<div class='table-responsive'>
  <table class='table table-hover'>
    <tr>
      <td>Puja</td>
      <td class='dtime'>4:00 am</td> 
    </tr>
    <tr>
      <td>Pushpanjali</td>
      <td class='dtime'>6:00 am</td> 
    </tr>
    <tr>
      <td>Bhog & Aarti</td>
      <td class='dtime'>6:30 am</td> 
    </tr>
    <tr>
      <td>Sandhi Puja</td>
      <td class='dtime'>8:05 am - 8:53 am</td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class="row">
  <div class="col-sm-6">
    <p id='event'>Maha Navami</p>
  </div>
  <div class="col-sm-6">
    <p id='italic'>October 2, 2014</p>
  </div>
</div>
<div class='table-responsive'>
  <table class='table table-hover'>
    <tr>
      <td>Puja</td>
      <td class='dtime'>10:00 am</td> 
    </tr>
    <tr>
      <td>Pushpanjali</td>
      <td class='dtime'>12:00 pm</td> 
    </tr>
    <tr>
      <td>Bhog & Aarti</td>
      <td class='dtime'>12:20 pm</td> 
    </tr>
    <tr>
      <td>HOM</td>
      <td class='dtime'>1:15 pm</td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class="row">
  <div class="col-sm-6">
    <p id='event'>Maha Dasami</p>
  </div>
  <div class="col-sm-6">
    <p id='italic'>October 3, 2014</p>
  </div>
</div>
<div class='table-responsive'>
  <table class='table table-hover'>
    <tr>
      <td>Puja</td>
      <td class='dtime'>6:30 am</td> 
    </tr>
    <tr>
      <td>Darpan Bisarjan</td>
      <td class='dtime'>7:00 am</td> 
    </tr>
    <tr>
      <td>Sindoor Utsab</td>
      <td class='dtime'>10:00 am</td> 
    </tr>
    <tr>
      <td>Immersion</td>
      <td class='dtime'>3:00 pm</td> 
    </tr>
    <tr>
      <td>Shantijal</td>
      <td class='dtime'>7:30 pm</td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

app/views/partials/_event_cultural.html.erb
<div class='table-responsive'>
  <table class='table'>
    <tr>
      <td class='align-date'>September 29, 2014</td>
      <td class='custom-align'>
        <p>Sharadiyo Abhinandan</p>
        <p>Bengali programme</p>
        <p>RD Burman a salute</p>
      </td>
      <td class='realign-image'><%= image_tag("event1.jpg", width: '120', class: 'img-thumbnail') %></td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class='table-responsive'>
  <table class='table'>
    <tr>
      <td class='align-date'>September 30, 2014</td>
      <td class='custom-align'>
        <p>Bengali Drama: 'Language'</p>
      </td>
      <td class='realign-image'><%= image_tag("event2.jpg", width: '120', class: 'img-thumbnail') %></td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class='table-responsive'>
  <table class='table'>
    <tr>
      <td class='align-date'>October 1, 2014</td>
      <td class='custom-align'>
        <p>Supratik</p>
        <p>Modern Bengali songs</p>
      </td>
      <td class='realign-image'><%= image_tag("event3.jpg", width: '120', class: 'img-thumbnail') %></td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

<div class='table-responsive'>
  <table class='table'>
    <tr>
      <td class='align-date'>October 2, 2014</td>
      <td class='custom-align'>
        <p>Zubin Garg Nite</p>
      </td>
      <td class='realign-image'><%= image_tag("event4.jpg", width: '120', class: 'img-thumbnail') %></td> 
    </tr>
  </table>
</div>
<!-- --------------------------- -->

app/views/partials/_flash_messages.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:success] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<ul class='nav nav-pills'>
  <li><%= link_to 'HOME', root_path %></li>
  <li><%= link_to 'GALLERY', contents_gallery_path, data: { turbolinks: false } %></li>
  <li><%= link_to 'EVENTS', contents_event_path %></li>
  <li><%= link_to 'COMMITTEE', contents_committee_path %></li>
  <li><%= link_to 'CONTACT US', contents_contact_path, data: { turbolinks: false } %></li>
</ul>

app/views/photos/_photo.html.erb
<% if current_user %>
    <li class="col-xs-2">
      <%= link_to photo, method: :delete, remote: true, id: "photo-#{photo.id}", data: {confirm: 'Are you sure?'} do %>
        <%= image_tag(photo.image.thumb('90x80#').url, class: 'img-responsive', class: 'img-thumbnail') %>
        <i class="glyphicon glyphicon-remove"> </i>
      <% end %> 
    </li>
<% else %>
  <li class="col-xs-2">
    <%= link_to image_tag(photo.image.thumb('90x80#').url, class: 'img-thumbnail'),
    photo.image.remote_url, rel: 'gallery', :data => { :colorbox_static => true}, target: '_blank' %>
  </li>
<% end %>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert('The photo could not be uploaded: <%= j @photo.errors.full_messages.join(', ').html_safe %>');
<% else %>
  $('#photos-list').prepend('<%= j render @photo %>');
<% end %>

app/views/photos/destroy.js.erb
$('#photo-' +<%= @photo.id %>).hide();

app/views/photos/new_multiple.html.erb
<div class='contents'>
  <h1>GALLERY</h1>
    <ul class="row" id="photos-list">
      <%= render @photos %>
    </ul>

  <!-- --------- ADDING ALBUMS ---------- -->

  <% if current_user %>
    <h3>Upload photos</h3>
    
    <%= form_for @photo, :html => {:class => 'form-horizontal' } do |f| %>

      <div class='column col-sm-3'>
        <div class="form-group">
          <%= f.file_field :image, required: true, multiple: true, name: 'photo[image]' %>
        </div>
      </div>
      </br></br></br></br>

      <div class="progress-wrapper">
        <p>Bitrate: <span class="bitrate"></span></p>
        <div class="progress">
          <div class="progress-bar" role="progressbar">
            0%
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<script>
$(document).ready(function() {
  var bitrate, multiple_photos_form, progress_bar, wrapper;
  multiple_photos_form = $("#new_photo");
  wrapper = multiple_photos_form.find(".progress-wrapper");
  bitrate = wrapper.find(".bitrate");
  progress_bar = wrapper.find(".progress-bar");
  multiple_photos_form.fileupload({
    dataType: "script",
    add: function(e, data) {
      var file, types;
      types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
      file = data.files[0];
      if (types.test(file.type) || types.test(file.name)) {
        return data.submit();
      } else {
        return alert(file.name + " must be GIF, JPEG, BMP or PNG file");
      }
    }
  });
  multiple_photos_form.on("fileuploadstart", function() {
    return wrapper.show();
  });
  multiple_photos_form.on("fileuploaddone", function() {
    wrapper.hide();
    return progress_bar.width(0);
  });
  return multiple_photos_form.on("fileuploadprogressall", function(e, data) {
    var progress;
    bitrate.text((data.bitrate / 1024).toFixed(2) + "Kb/s");
    progress = parseInt(data.loaded / data.total * 100, 10);
    return progress_bar.css("width", progress + "%").text(progress + "%");
  });
});
</script>

app/views/welcomes/index.html.erb
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("slide1.jpg", class: 'img-thumbnail', class: 'img-responsive') %>
    </div>
    <div class="item">
      <%= image_tag("slide2.jpg", class: 'img-thumbnail', class: 'img-responsive') %>
    </div>
    <div class="item">
      <%= image_tag("slide3.jpg", class: 'img-thumbnail', class: 'img-responsive') %>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>  
</div>
<p id="index-content">
  The Notunpalli Durgotsab Committee has come a long way since its inception 42 years ago in Bandra, Mumbai. From a band of a few dedicated members who wanted to usher in the beauty and the fervor of Durga Puja from its native land Bengal to the metro, the puja has grown magnanimously encompassing one and all who wish to join in its gaiety.

  While prayers fill in the morning hours with the resounding drums or dhaks that reverberate the dervish frenzy of devotees, the evenings strum with music, dance and drama with around 1 lakh people participating in the puja celebrations. All devotees partake the bhog (Prasad) in the afternoon that is served with warmth and the deep philosophy that Service to Man is Service to God. Over 20,000 devotees are served the warm bhog throughout the puja that spreads the feeling of oneness. 
   
  On one hand it is a cultural amalgamation of sorts but on the other, the Committee also shares social responsibility in the fields of health and education. Notunpalli Durgotsab has participants from the world over who share the feeling of being part of a big family with the common belief that the festival of the Goddess Durga, the icon of mighty womanhood, is the celebration that destroys the evil and welcomes all that is good, true and victorious. 
   
  Come and join us in this eternal festivity of joy and togetherness.
</p>